### ISSUE TITLE
Don't minimise npm package?

### ISSUE THREAD

**Issue by mmkal** [privatenumber/cleye#30]
### Feature request

It would be nice to publish cleye without minimised javascript

### Why?

Being minimised makes it very hard to debug things, here's the error I'm currently looking at (note, this issue isn't about the error, I'm playing around and no doubt did something wrong, it's more about how hard it is to find out _what_ I did wrong):

<img width="1420" alt="image" src="https://github.com/privatenumber/cleye/assets/15040698/c032c9d6-dfb5-4f2f-9192-eea778163d1c">

(Another alternative: have really really bulletproof input validation, so end-users like me never see this kind of error, but I don't think that's easily achievable)

### Alternatives

Publish source maps, and the original typescript too, so users can use a library like `source-map-support` to get a more human readable stack trace.

### Additional context

I don't think there's much value in minimising, especially since this is a CLI library, not a browser library. The rare people who want minimised code can always use their own minimiser.

**Comment by privatenumber** [comment]
Maybe I'll write a blog post on why I minify my packages one day.

But if you want to debug cleye, you can run prettier on it.

If the error message is not ideal, that's Node.js printing it so I think there should be a feature request to better handle error stacks in minified/dense code.
